name = "ThreadPools"
uuid = "b189fb0b-2eb5-4ed4-bc0c-d34c51242431"
authors = ["Trey Roessig <roessig.trey@gmail.com"]
version = "0.1.0"

[deps]
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"

[compat]
julia = "1.3"
